// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOpS_FOobQEpl9ibY1fROB0dcdNMvXvHk',
    appId: '1:498439469624:web:a6e738ff116c9d488b84cd',
    messagingSenderId: '498439469624',
    projectId: 'relojeria-app-90b6d',
    authDomain: 'relojeria-app-90b6d.firebaseapp.com',
    databaseURL: 'https://relojeria-app-90b6d-default-rtdb.firebaseio.com',
    storageBucket: 'relojeria-app-90b6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlIeB22bQgIsaowpzjFZXCcL4UK2j6J1E',
    appId: '1:498439469624:android:904f38fc29f8aac38b84cd',
    messagingSenderId: '498439469624',
    projectId: 'relojeria-app-90b6d',
    databaseURL: 'https://relojeria-app-90b6d-default-rtdb.firebaseio.com',
    storageBucket: 'relojeria-app-90b6d.firebasestorage.app',
  );
}
